export default {
  "channels": { title: "channels" },
  "port-id": { title: "ports/(port_id)" },
  "client-state": { title: "(port_id)/client_state" },
  "revision-height": { title: "height/(revision_height)" },
  "next-sequence": { title: "(port_id)/next_sequence" },
  "packet-acknowledgements": { title: "(port_id)/packet_acknowledgements" },
  "sequence": { title: "packet_acks/(sequence)" },
  "packet-commitments": { title: "(port_id)/packet_commitments" },
  "unreceived-acks": { title: "(packet_ack_sequences)/unreceived_acks" },
  "unreceived-packets": { title: "(packet_commitment_sequences)/unreceived_packets" },
  "sequence": { title: "packet_commitments/(sequence)" },
  "sequence": { title: "packet_receipts/(sequence)" },
  "channels": { title: "(connection)/channels" },
  "client-states": { title: "client_states" },
  "client-id": { title: "client_states/(client_id)" },
  "client-id": { title: "client_status/(client_id)" },
  "client-id": { title: "consensus_states/(client_id)" },
  "heights": { title: "(client_id)/heights" },
  "revision-height": { title: "height/(revision_height)" },
  "upgraded-client-states": { title: "upgraded_client_states" },
  "upgraded-consensus-states": { title: "upgraded_consensus_states" },
  "client-id": { title: "client_connections/(client_id)" },
  "connections": { title: "connections" },
  "connection-id": { title: "connections/(connection_id)" },
  "client-state": { title: "(connection_id)/client_state" },
  "revision-height": { title: "height/(revision_height)" }
};
