export default {
	denom: { title: 'asset_list/(denom)' },
	'num-of-periods': { title: '(periodLengthInSeconds)/(numOfPeriods)' },
	'asset-denom': { title: '(priceDenom)/(assetDenom)' },
	'lookback-in-seconds': { title: '(assetDenom)/(lookbackInSeconds)' },
	id: { title: '(assetDenom)/(id)' },
	account: { title: '(contractAddr)/(account)' },
	timestamp: { title: '(assetDenom)/(timestamp)' },
	'lookback-seconds': { title: '(contractAddr)/(lookbackSeconds)' },
	price: { title: '(assetDenom)/(price)' },
	'contract-addr': { title: 'registered_contract/(contractAddr)' },
	epoch: { title: 'epoch/epoch' },
	'evm-address': { title: 'evm/evm_address' },
	pointer: { title: 'evm/pointer' },
	'pointer-version': { title: 'evm/pointer_version' },
	'sei-address': { title: 'evm/sei_address' },
	'static-call': { title: 'evm/static_call' },
	metadata: { title: 'denoms/metadata' },
	'authority-metadata': { title: '(denom)/authority_metadata' },
	creator: { title: 'denoms_from_creator/(creator)' },
	params: { title: 'tokenfactory/params' }
};
