export default {
  "index": { title: "Overview" },
  "asset-list": { title: "dex/asset_list" },
  "denom": { title: "asset_list/(denom)" },
  "numOfPeriods": { title: "(periodLengthInSeconds)/(numOfPeriods)" },
  "assetDenom": { title: "(priceDenom)/(assetDenom)" },
  "lookbackInSeconds": { title: "(assetDenom)/(lookbackInSeconds)" },
  "id": { title: "(assetDenom)/(id)" },
  "account": { title: "(contractAddr)/(account)" },
  "timestamp": { title: "(assetDenom)/(timestamp)" },
  "lookbackSeconds": { title: "(contractAddr)/(lookbackSeconds)" },
  "price": { title: "(assetDenom)/(price)" },
  "params": { title: "dex/params" },
  "contractAddr": { title: "registered_contract/(contractAddr)" },
  "registered-pairs": { title: "dex/registered_pairs" },
  "epoch": { title: "epoch/epoch" },
  "params": { title: "epoch/params" },
  "evm-address": { title: "evm/evm_address" },
  "pointer": { title: "evm/pointer" },
  "pointer-version": { title: "evm/pointer_version" },
  "sei-address": { title: "evm/sei_address" },
  "static-call": { title: "evm/static_call" },
  "metadata": { title: "denoms/metadata" },
  "authority-metadata": { title: "(denom)/authority_metadata" },
  "creator": { title: "denoms_from_creator/(creator)" },
  "params": { title: "tokenfactory/params" }
};
