name: Broken URL Check

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:  # Allows manual triggering of the workflow

defaults:
  run:
    shell: bash

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run link checker
        run: python scripts/urlcheck.py
        env:
          CHECK_PATH: './pages/'  # Set the CHECK_PATH environment variable here

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: 'Broken URLs detected',
              body: 'The URL checking script has detected one or more broken URLs. Please check the workflow logs for details.'
            })

      - name: Upload Check Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: url-check-results
          path: url_check_results.txt
