name: Broken URL Check

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  url-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run link checker
        id: run_checker
        run: |
          output=$(python scripts/urlcheck.py)
          echo "checker_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          CHECK_PATH: './pages/'

      - name: Create Issue with Results
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = JSON.parse('${{ steps.run_checker.outputs.checker_output }}');
            const issueTitle = output.status === "issues_found" 
              ? `Broken URLs Detected: ${output.total_issues} issues found`
              : "URL Check Completed - No Issues Found";
            
            let issueBody = `# URL Check Results\n\n`;
            if (output.status === "issues_found") {
              issueBody += `## Issues Found: ${output.total_issues}\n\n`;
              output.issues.forEach(issue => {
                issueBody += `- File: ${issue.file}, Line: ${issue.line}\n`;
                issueBody += `  URL: ${issue.url}\n`;
                issueBody += `  Status Code: ${issue.status_code}, Reason: ${issue.reason}\n`;
                issueBody += `  Final URL: ${issue.final_url}\n\n`;
              });
            } else {
              issueBody += "No broken URLs detected in this check.";
            }
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.name,
              title: issueTitle,
              body: issueBody,
              labels: ['url-check']
            });
